

== Instalación

=== Instalar Grafana

Esta sección analiza los requisitos de hardware y software, así como el proceso de instalación de Grafana en diferentes sistemas operativos. Esta sección tiene los siguientes temas:

* [Requisitos]
* [Instalar en Debian o Ubuntu]
* [Instalar en Linux basado en RPM (CentOS, Fedora, OpenSuse, RedHat)]
* [Instalar en macOS]
* [Instalar en Windows]
* [Ejecutar imagen de Docker]
* [Implementar Grafana en Kubernetes]

Para obtener instrucciones de actualización, consulte [Actualizar Grafana]. Para reiniciar Grafana, consulte [Reiniciar Grafana].

Para instalar Grafana Enterprise, consulte las instrucciones para instalar Grafana en su sistema. Luego, consulte [Activar una licencia empresarial].

=== Requisitos

==== Requisitos de Grafana

Esta página enumera los requisitos mínimos de hardware y software para instalar Grafana.

Para ejecutar Grafana, debe tener un sistema operativo compatible, hardware que cumpla o supere los requisitos mínimos, una base de datos compatible y un navegador compatible.

Grafana utiliza otro software de código abierto. Consulte [package.json] para obtener una lista completa.

===== Sistemas operativos compatibles

Los siguientes sistemas operativos son compatibles con la instalación de Grafana:

* [Debian / Ubuntu]
* [Linux basado en RPM (CentOS, Fedora, OpenSuse, RedHat)]
* [Mac OS]
* [Windows]

La instalación de Grafana en otros sistemas operativos es posible, pero no se recomienda ni se admite.

===== Recomendaciones de hardware

Grafana no usa muchos recursos y es muy liviano en el uso de memoria y CPU.

Memoria mínima recomendada: 255 MB, CPU mínimo recomendado: 1

Algunas funciones pueden requerir más memoria o CPU. Las características que requieren más recursos incluyen:

* Representación de imágenes del lado del servidor
* Alertas
* Proxy de fuente de datos

===== Bases de datos compatibles

Grafana requiere una base de datos para almacenar sus datos de configuración, como usuarios, fuentes de datos y tableros. Los requisitos exactos dependen del tamaño de la instalación de Grafana y de las funciones utilizadas.

Grafana admite las siguientes bases de datos:

* SQLite
* MySQL
* PostgreSQL

De forma predeterminada, Grafana instala y usa SQLite, que es una base de datos incrustada almacenada en la ubicación de instalación de Grafana.

****
*Nota:* Las versiones 9.5.18, 9.4.23, 9.6.14, 10.9, 11.4 y 12-beta2 de PostgreSQL se ven afectadas por un error (registrado por el proyecto PostgreSQL como [error /*15865]) que impide que esas versiones se utilicen con Grafana. El error se ha corregido en versiones más recientes de PostgreSQL.
****

===== Navegadores web compatibles

Grafana es compatible con la versión actual de los siguientes navegadores. Es posible que las versiones anteriores de estos navegadores no sean compatibles, por lo que siempre debe actualizar a la última versión cuando utilice Grafana.

* Chrome / Chromium
* Firefox
* Safari
* Microsoft Edge
* Internet Explorer 11 solo es totalmente compatible con las versiones de Grafana anteriores a la v6.0.

****
*Nota:* habilite siempre JavaScript en su navegador. No se admite la ejecución de Grafana sin JavaScript habilitado en el navegador.
****

=== Instalar en Windows

==== Instalar en Windows

Puede descargar el paquete de instalación de Windows o un archivo binario de Windows independiente.

Lea [Actualizando Grafana] para obtener sugerencias y orientación sobre cómo actualizar una instalación existente.

[arabic]
. Navegue hasta [Descargar Grafana].
. Seleccione la versión de Grafana que desee instalar.
* La versión más reciente de Grafana está seleccionada de forma predeterminada.
* El campo *Versión* muestra solo las versiones terminadas. Si desea instalar una versión beta, haga clic en *Nightly Builds* y luego seleccione una versión.
. Seleccione una *Edición*.
* *Enterprise*: descarga recomendada. Funcionalmente idéntico a la versión de código abierto, pero incluye características que puede desbloquear con una licencia si así lo desea.
* *Open Source*: funcionalmente idéntico a la versión empresarial, pero deberá descargar la versión empresarial si desea funciones empresariales.
. Haga clic en *Windows*.

Puede utilizar el instalador de Windows o puede instalar un binario de Windows independiente.

===== Instalar con el instalador de Windows (recomendado)

[arabic]
. Haz clic en *Descargar el instalador*.
. Abra y ejecute el instalador.

Para ejecutar Grafana, abra su navegador y vaya al puerto de Grafana (http:/ localhost:3000/ es el predeterminado) y luego siga las instrucciones en [Comenzando].

===== Instalar binario de Windows independiente

[arabic]
. Haga clic en *Descargar el archivo zip*. *Importante:* Una vez que haya descargado el archivo zip y antes de extraerlo, asegúrese de abrir las propiedades de ese archivo (haga clic con el botón derecho en *Propiedades*) y seleccione la casilla de verificación ˋdesbloquearˋ y luego haga clic en ˋAceptarˋ.
. Extraiga esta carpeta a cualquier lugar desde donde desee que se ejecute Grafana.
. Inicie Grafana ejecutando ˋgrafana-server.exeˋ, ubicado en el directorio bin, preferiblemente desde la línea de comandos. Si desea ejecutar Grafana como un servicio de Windows, descargue NSSM. Es muy fácil agregar Grafana como un servicio de Windows usando esa herramienta.

Para ejecutar Grafana, abra su navegador y vaya al puerto de Grafana (http://localhost:3000/ es el predeterminado) y luego siga las instrucciones en Comenzando.

****
*Nota:* El puerto Grafana predeterminado es ˋ3000ˋ. Este puerto puede requerir permisos adicionales en Windows. Si no aparece en el puerto predeterminado, puede intentar cambiar a un puerto diferente.
****

[arabic]
. Vaya al directorio ˋconfˋ y copie ˋsample.iniˋ en ˋcustom.iniˋ. *Nota:* debe editar ˋcustom.iniˋ, nunca ˋdefaults.iniˋ.
. Edite ˋcustom.iniˋ y elimine el comentario de la opción de configuración ˋhttp_portˋ (ˋ;ˋ es el carácter de comentario en los archivos ini) y cámbielo a algo como ˋ8080ˋ o similar. Ese puerto no debería requerir privilegios adicionales de Windows. Lea más sobre las opciones de configuración.

=== Actualizar Grafana

==== Actualizar Grafana

Le recomendamos que actualice Grafana con frecuencia para mantenerse al día con las últimas correcciones y mejoras. Para que esto sea una realidad, las actualizaciones de Grafana son compatibles con versiones anteriores y el proceso de actualización es simple y rápido.

La actualización es generalmente segura (entre muchas versiones menores y una principal) y los tableros y los gráficos tendrán el mismo aspecto. Puede haber pequeños cambios importantes en algunos casos extremos, que se describen en las [Notas de la versión] y el [Registro de cambios].

===== Respaldo

Le recomendamos que haga una copia de seguridad de algunas cosas en caso de que tenga que revertir la actualización.

* Complementos instalados: realice una copia de seguridad de ellos antes de actualizarlos en caso de que desee revertir la versión de Grafana y desee obtener exactamente las mismas versiones que estaba ejecutando antes de la actualización.
* No es necesario hacer una copia de seguridad de los archivos de configuración. Sin embargo, es posible que desee hacerlo en caso de que agregue nuevas opciones de configuración después de la actualización y luego retroceda.

====== Copia de seguridad de la base de datos

Antes de actualizar, puede ser una buena idea hacer una copia de seguridad de su base de datos de Grafana. Esto asegurará que siempre pueda volver a su versión anterior. Durante el inicio, Grafana migrará automáticamente el esquema de la base de datos (si hay cambios o tablas nuevas). A veces, esto puede causar problemas si luego desea cambiar a una versión anterior.

*sqlite*

Si usa sqlite, solo necesita hacer una copia de seguridad de su archivo ˋgrafana.dbˋ. Normalmente se encuentra en ˋ/var/lib/grafana/grafana.dbˋ en sistemas Unix. Si no está seguro de qué base de datos utiliza y dónde está almacenada, consulte el archivo de configuración de grafana. Si instaló grafana en una ubicación personalizada utilizando un tar/zip binario, generalmente se encuentra en ˋ<grafana_install_dir> / dataˋ.

*mysql*

ˋbackup:
> mysqldump -u root -p[root_password] [grafana]> grafana_backup.sql

restore:
> mysql -u root -p grafana < grafana_backup.sqlˋ

*postgres*

ˋbackup:
> pg_dump grafana > grafana_backup

restore:
> psql grafana < grafana_backupˋ

====== Windows

Si descargó el paquete binario de Windows, puede descargar un paquete más nuevo y extraerlo en la misma ubicación (y sobrescribir los archivos existentes). Esto podría sobrescribir los cambios de configuración. Le recomendamos que guarde sus cambios de configuración en un archivo llamado ˋ<grafana_install_dir> /conf/custom.iniˋ ya que esto facilitará las actualizaciones sin correr el riesgo de perder sus cambios de configuración.

===== Actualizar complementos

Una vez que haya actualizado, le recomendamos encarecidamente que actualice todos sus complementos, ya que una nueva versión de Grafana puede hacer que los complementos más antiguos dejen de funcionar correctamente.

Puede actualizar todos los complementos usando

ˋgrafana-cli plugins update-allˋ

=== Reiniciar Grafana

==== Reiniciar Grafana

Los usuarios a menudo necesitan reiniciar Grafana después de haber realizado cambios de configuración. Este tema proporciona instrucciones detalladas sobre cómo reiniciar en los sistemas operativos compatibles con Grafana.

===== Windows

Para reiniciar Grafana:

[arabic]
. [Abra la aplicación Servicios.]
. [Haga clic con el botón derecho en el servicio *Grafana*.]
. [En el menú contextual, haga clic en *Reiniciar*].